config/routes.rb
Rails.application.routes.draw do
  root to: 'clocks#index'

  resources :clocks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock.rb
class Clock < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clocks_controller.rb
class ClocksController < ApplicationController
  def index
    @clocks = Clock.all
    @clock = Clock.new
  end

  def create
    @clock = Clock.create(clock_params)
    @clock.time = @clock.time + "#{@clock.timezone}00000".to_i
    @clock.save!
  end

  def show
    @clock = Clock.find(params[:id])
  end

  private

  def clock_params
    params.fetch(:clock).permit(:time, :timezone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clocks_helper.rb
module ClocksHelper
end

app/views/clocks/index.html.erb
<h1> New clock </h1>

<%= form_for @clock do |f| %>
  <%= f.label :time %>
  <%= f.time_field :time %>
  <%= f.number_field :timezone, in: -12..12 %>
  <%= f.submit %>
<% end %>

<h1> Clocks: </h1>
<ul>
  <% @clocks.each do |clock| %>
    <li> <%= clock.time %> </li>
    <%= link_to 'time zones', clock_path(clock.id) %>
  <% end %>
</ul>

app/views/clocks/show.html.erb
<h1> This clock: </h1>

<h3> Timezones </h3>

<%= link_to '-11 UTC', edit_clock_path, data: { tz: -11 } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>